# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.worldbank.com:
  peer0.xbank.worldbank.com:
  peer0.hdfc.worldbank.com:
  peer0.tatasteel.worldbank.com:
  peer0.lnt.worldbank.com:
  peer0.fedx.worldbank.com:
  peer0.sebi.worldbank.com:
  
networks:
  worldbank:

services:
  orderer.worldbank.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.worldbank.com
    container_name: orderer.worldbank.com
    networks:
      - worldbank

  peer0.xbank.worldbank.com:
    container_name: peer0.xbank.worldbank.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.xbank.worldbank.com
    networks:
      - worldbank

  peer0.hdfc.worldbank.com:
    container_name: peer0.hdfc.worldbank.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hdfc.worldbank.com
    networks:
      - worldbank

  peer0.tatasteel.worldbank.com:
    container_name: peer0.tatasteel.worldbank.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.tatasteel.worldbank.com
    networks:
      - worldbank