# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.worldbank.com:
    container_name: orderer.worldbank.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/worldbank.com/orderers/orderer.worldbank.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/worldbank.com/orderers/orderer.worldbank.com/tls/:/var/hyperledger/orderer/tls
        - orderer.worldbank.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.xbank.worldbank.com:
    container_name: peer0.xbank.worldbank.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.xbank.worldbank.com
      - CORE_PEER_ADDRESS=peer0.xbank.worldbank.com:9001
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9001
      - CORE_PEER_CHAINCODEADDRESS=peer0.xbank.worldbank.com:9002
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9002
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.xbank.worldbank.com:9001
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.xbank.worldbank.com:9001
      - CORE_PEER_LOCALMSPID=xbankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/xbank.worldbank.com/peers/peer0.xbank.worldbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/xbank.worldbank.com/peers/peer0.xbank.worldbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.xbank.worldbank.com:/var/hyperledger/production
    ports:
      - 9001:9001

  peer0.hdfc.worldbank.com:
    container_name: peer0.hdfc.worldbank.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hdfc.worldbank.com
      - CORE_PEER_ADDRESS=peer0.hdfc.worldbank.com:9011
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9011
      - CORE_PEER_CHAINCODEADDRESS=peer0.hdfc.worldbank.com:9012
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9012
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hdfc.worldbank.com:9011
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hdfc.worldbank.com:9011
      - CORE_PEER_LOCALMSPID=hdfcMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hdfc.worldbank.com/peers/peer0.hdfc.worldbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hdfc.worldbank.com/peers/peer0.hdfc.worldbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.hdfc.worldbank.com:/var/hyperledger/production
    ports:
      - 9011:9011

    
  peer0.tatasteel.worldbank.com:
    container_name: peer0.tatasteel.worldbank.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.tatasteel.worldbank.com
      - CORE_PEER_ADDRESS=peer0.tatasteel.worldbank.com:9021
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9021
      - CORE_PEER_CHAINCODEADDRESS=peer0.tatasteel.worldbank.com:9022
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9022
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.tatasteel.worldbank.com:9021
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.tatasteel.worldbank.com:9021
      - CORE_PEER_LOCALMSPID=tatasteelMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/tatasteel.worldbank.com/peers/peer0.tatasteel.worldbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/tatasteel.worldbank.com/peers/peer0.tatasteel.worldbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.tatasteel.worldbank.com:/var/hyperledger/production
    ports:
      - 9021:9021

  peer0.lnt.worldbank.com:
    container_name: peer0.lnt.worldbank.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.lnt.worldbank.com
      - CORE_PEER_ADDRESS=peer0.lnt.worldbank.com:9031
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9031
      - CORE_PEER_CHAINCODEADDRESS=peer0.lnt.worldbank.com:9032
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9032
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.lnt.worldbank.com:9031
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.lnt.worldbank.com:9031
      - CORE_PEER_LOCALMSPID=lntMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/lnt.worldbank.com/peers/peer0.lnt.worldbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/lnt.worldbank.com/peers/peer0.lnt.worldbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.lnt.worldbank.com:/var/hyperledger/production
    ports:
      - 9031:9031

  peer0.fedx.worldbank.com:
    container_name: peer0.fedx.worldbank.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.fedx.worldbank.com
      - CORE_PEER_ADDRESS=peer0.fedx.worldbank.com:9041
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9041
      - CORE_PEER_CHAINCODEADDRESS=peer0.fedx.worldbank.com:9042
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9042
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.fedx.worldbank.com:9041
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.fedx.worldbank.com:9041
      - CORE_PEER_LOCALMSPID=fedxMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/fedx.worldbank.com/peers/peer0.fedx.worldbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/fedx.worldbank.com/peers/peer0.fedx.worldbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.fedx.worldbank.com:/var/hyperledger/production
    ports:
      - 9041:9041
  

  peer0.sebi.worldbank.com:
    container_name: peer0.sebi.worldbank.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.sebi.worldbank.com
      - CORE_PEER_ADDRESS=peer0.sebi.worldbank.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.sebi.worldbank.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.sebi.worldbank.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.sebi.worldbank.com:9051
      - CORE_PEER_LOCALMSPID=sebiMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/sebi.worldbank.com/peers/peer0.sebi.worldbank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/sebi.worldbank.com/peers/peer0.sebi.worldbank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.sebi.worldbank.com:/var/hyperledger/production
    ports:
      - 9051:9051